# This specifies the number of layers and number of hidden neurons in each layer.
# Note that the first and the last elements of the list indicate the input and
# output sizes
layer_specs: [6, 128, 128, 2]

# The learning rate to be used for training.
learning_rate: 0.1

# Number of training samples per batch to be passed to network
batch_size: 128

# Number of epochs to train the model
epochs: 400

# Regularization constant
L2_penalty: 0.2
regularization_type: "L2"
regularization_gamma: 0.01

# Use momentum for training
momentum: True

# Value for the parameter 'gamma' in momentum
momentum_gamma: 0.5